# Generated by Django 3.1.1 on 2020-09-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.PositiveBigIntegerField()),
                ('text', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=130, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=40)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
