# Generated by Django 3.1.1 on 2020-09-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tweet_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
