# Generated by Django 3.1.1 on 2020-09-08 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_articlelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlabel',
            name='article_label',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_labels', to='api.articlelabel'),
            preserve_default=False,
        ),
    ]
