# Generated by Django 3.1.1 on 2020-09-10 17:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_commentlabel_article_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlelabel',
            unique_together={('user', 'article')},
        ),
    ]
