# Generated by Django 3.1.1 on 2020-09-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200910_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlabel',
            name='type',
            field=models.CharField(choices=[('MUJER', 'Violencia contra las mujeres'), ('GENERO', 'Identidad de género u orientación sexual'), ('RACISMO', 'Racismo o xenofobia'), ('POBREZA', 'Pobreza, situación socioeconómica, barrio de residencia'), ('RELIGION', 'Religión'), ('DISCAPACIDAD', 'Discapacidad o Salud Mental')], default='MUJER', max_length=15),
            preserve_default=False,
        ),
    ]
