# Generated by Django 3.1.1 on 2020-09-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_commentlabel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlabel',
            name='calls_for_action',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentlabel',
            name='type',
            field=models.CharField(choices=[('', 'Ninguno'), ('MUJER', 'Violencia contra las mujeres'), ('GENERO', 'Identidad de género u orientación sexual'), ('RACISMO', 'Racismo o xenofobia'), ('POBREZA', 'Pobreza, situación socioeconómica, barrio de residencia'), ('RELIGION', 'Religión'), ('DISCAPACIDAD', 'Discapacidad o Salud Mental')], max_length=15),
        ),
    ]
