# Generated by Django 3.1.1 on 2020-09-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200913_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tweet_id',
            field=models.PositiveBigIntegerField(db_index=True, unique=True),
        ),
    ]
