# Generated by Django 3.1.1 on 2020-10-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201023_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlabel',
            name='against_aspect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentlabel',
            name='against_criminals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentlabel',
            name='against_others',
            field=models.BooleanField(default=False),
        ),
    ]
