# Generated by Django 3.1.2 on 2020-10-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201026_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelabel',
            name='metadata',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
