# Generated by Django 3.1.4 on 2020-12-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_batch_batcharticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='articles',
            field=models.ManyToManyField(through='api.BatchArticle', to='api.Article'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
