# Generated by Django 3.1.4 on 2020-12-28 21:27

import api.models.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0020_auto_20201228_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, api.models.mixins.Completable),
        ),
        migrations.AddField(
            model_name='batch',
            name='users',
            field=models.ManyToManyField(through='api.BatchAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
