# Generated by Django 3.1.4 on 2021-01-08 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0023_auto_20201229_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelabel',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='articlelabel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_labels', to=settings.AUTH_USER_MODEL),
        ),
    ]
