# Generated by Django 3.1.5 on 2021-01-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_batchassignment_completed_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='skippable',
            field=models.BooleanField(default=True),
        ),
    ]
