# Generated by Django 3.1.5 on 2021-01-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_assignment_skippable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='users',
        ),
    ]
