# Generated by Django 3.1.5 on 2021-01-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_batch_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchAssignment',
        ),
    ]
