# Generated by Django 3.1.5 on 2021-01-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210120_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='comment',
            new_name='comments',
        ),
    ]
