# Generated by Django 3.1.5 on 2021-01-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_delete_batchassignment'),
        ('api', '0028_auto_20210121_1831'),
    ]

    operations = [
    ]
