# Generated by Django 3.1.5 on 2021-01-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20210122_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='reassigned',
            field=models.BooleanField(default=False),
        ),
    ]
