# Generated by Django 3.1.5 on 2021-02-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_assignment_reassigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelabel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
