# Generated by Django 3.1.5 on 2021-02-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_articlelabel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelabel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
