name: run_tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync
